import { StyleSheet } from "react-native";
import { useFonts } from "expo-font";

function loadFonts() {
  const [loaded] = useFonts({
    SFUITextRegular: require("./assets/fonts/SFUITextRegular.otf"),
    SFProTextLight: require("./assets/fonts/SFProTextLight.otf"),
    SFProTextSemibold: require("./assets/fonts/SFProTextSemibold.otf"),
  });
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FcFcFc",
    alignItems: "center",
    justifyContent: "center",
  },
  stripContainer: { flex: 1 },
  dateNumberStyle: { color: "#222222", fontSize: 14 },
  dateNameStyle: { color: "#222222", fontSize: 9 },
  calendarTitle: {
    fontFamily: "SFProTextSemibold",
    fontSize: 12,
  },
  calendarDescription: {
    fontFamily: "SFUITextRegular",
    fontSize: 10,
    color: "#222222",
  },
  calendarAttachment: {
    fontFamily: "SFUITextRegular",
    fontSize: 10,
    color: "#222222",
    marginLeft: 2,
  },
  // Details screen
  detailsContainer: {
    backgroundColor: "#FcFcFc",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    paddingTop: 20,
    paddingHorizontal: 30,
    flex: 1,
    paddingBottom: 10,
    borderBottomColor: "black",
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  detailsTitle: {
    fontFamily: "SFProTextSemibold",
    fontSize: 26,
    marginBottom: 5,
    color: "#222222",
  },
  detailsTime: {
    fontFamily: "SFUIProLight",
    fontSize: 20,
    color: "#8A8A8A",
    marginBottom: 20,
  },
  detailsDescription: {
    fontFamily: "SFUITextRegular",
    fontSize: 14,
    marginBottom: 20,
    color: "#222222",
  },
  eventTitle: {
    fontFamily: "SFProTextMedium",
    fontSize: 26,
    color: "#222222",
    alignSelf: "flex-start",
    paddingLeft: 0,
  },
  eventColor: {
    fontSize: 16,
    fontFamily: "SFProTextMedium",
    color: "#111111",
    marginRight: 20,
    flexDirection: "row",
  },
  eventTimeContainer: {
    flex: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 10,
    alignSelf: "stretch",
  },
  eventTimeText: {
    fontFamily: "SFProTextLight",
    fontSize: 16,
    color: "#111111",
    marginRight: 25,
  },
  eventTimeSelect: {
    flex: 1,
    paddingLeft: 20,
    paddingVertical: 10,
    flexDirection: "row",
    backgroundColor: "#EFEFEF",
    alignItems: "center",
    justifyContent: "center",
    elevation: 1,
    borderRadius: 5,
  },
  eventTimeSelectButton: {
    paddingRight: 15,
    paddingLeft: 25,
  },
  eventDescriptionInput: {
    fontFamily: "SFProTextLight",
    fontSize: 16,
    color: "#222222",
    alignSelf: "stretch",
    paddingVertical: 3,
  },
  eventDescriptionText: {
    marginTop: 20,
    fontFamily: "SFProTextMedium",
    fontSize: 16,
    marginBottom: 5,
    color: "#222222",
  },
  eventAddEventButtonText: {
    fontFamily: "SFProTextSemibold",
    fontSize: 24,
    color: "#FFFFFF",
    alignSelf: "center",
    marginHorizontal: "auto",
  },
  eventAddEventButtonContainer: {
    paddingHorizontal: 15,
    paddingVertical: 10,
    backgroundColor: "#343950",
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginTop: 25,
    marginBottom: 20,
  },
  eventAttachButtonContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#52555B",
    borderRadius: 5,
    paddingLeft: 10,
    paddingVertical: 7,
    paddingRight: 13,
    alignSelf: "center",
  },
  eventAttachButtonText: {
    fontFamily: "SFProTextLight",
    fontSize: 12,
    color: "#FFFFFF",
    marginLeft: 5,
  },
  libraryContainer: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "stretch",
    paddingTop: 30,
  },
  libraryButton: {
    width: 300,
    marginLeft: 10,
    marginRight: 5,
    alignItems: "flex-start",
    backgroundColor: "#E1E8FF",
    padding: 15,
    marginVertical: 15,
    borderRadius: 20,
  },
  libraryImageContainer: {
    alignSelf: "stretch",
    alignItems: "center",
    justifyContent: "center",
    aspectRatio: 129 / 83,
  },
  libraryImage: {
    resizeMode: "cover",
    borderRadius: 10,
    flex: 1,
    aspectRatio: 129 / 83,
    alignSelf: "center",
  },
  libraryDocumentaryWrapper: {
    borderRadius: 10,
    paddingVertical: 2,
    paddingHorizontal: 5,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  libraryDocumentaryText: {
    fontSize: 10,
    fontFamily: "SFProTextSemibold",
    color: "#FFF",
  },
  libraryHeader: {
    fontFamily: "SFProTextSemibold",
    fontSize: 24,
    color: "#0C5B43",
  },
  libraryDescription: {
    fontFamily: "SFProTextMedium",
    fontSize: 10,
    color: "#575050",
    marginTop: 10,
  },
  statusTitle: {
    fontFamily: "SFProTextSemibold",
    fontSize: 16,
    color: "#FFF",
    marginLeft: 10,
  },
  statusDescription: {
    fontFamily: "SFProTextLight",
    marginTop: -3,
    fontSize: 12,
    color: "#FFF",
    marginLeft: 10,
  },
  statusContainer: {
    paddingRight: 20,
    alignSelf: "center",
    position: "relative",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  signInContainer: {
    flex: 1,
    alignItems: "flex-start",
    justifyContent: "center",
    paddingHorizontal: 45,
  },
  signInTextInput: {
    flex: 1,
    marginTop: Platform.OS === "ios" ? 10 : -2,
    marginLeft: 12,
    color: "#05375a",
    borderBottomColor: "#6E6C78",
    borderBottomWidth: 1,
    paddingHorizontal: -3,
    marginRight: 20,
    fontFamily: "SFProTextMedium",
    fontSize: 14,
    color: "#111111",
    paddingTop: 4,
    marginBottom: 10,
  },
});

export default styles;
